# Generated by Django 5.0.2 on 2024-02-29 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_alter_customuser_password_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='screen',
        ),
        migrations.AddField(
            model_name='seat',
            name='show',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='back.show'),
            preserve_default=False,
        ),
    ]
